version: "3.7"
services:
  frontend:
    build:
      context: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend-php-fpm

  backend:
    build:
      context: backend/docker/development/nginx
    ports:
      - "8000:80"
    volumes:
      - ./backend:/app
    depends_on:
      - backend-php-fpm

  backend-php-fpm:
    build:
      context: backend/docker/development/php-fpm
    volumes:
      - ./backend:/app
    depends_on:
      - backend-mysql

  backend-php-cli:
    build:
      context: backend/docker/development/php-cli
    volumes:
      - ./backend:/app
    depends_on:
      - backend-mysql

  backend-mysql:
    image: mysql:8.0
    volumes:
      - ./data/mysql:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=secret"
      - "MYSQL_USER=app"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_DATABASE=directory"
    ports:
      - "33061:3306"
  backend-phpmyadmin:
    image: phpmyadmin
    restart: always
    links:
      - backend-mysql
    ports:
      - "8085:80"
    environment:
      - PMA_ARBITRARY=1
